// src/api/guardiansData.js
// Datos dummy de guardianes de América Latina

export const GUARDIANS_DATA = [
  {
    id: "1",
    name: "Valentina Ríos",
    role: "Directora de Conservación",
    organization: "Bosques Vivos A.C.",
    country: "México",
    category: "bioregion",
    badge_text: "Selva Maya",
    image_url: "https://randomuser.me/api/portraits/women/11.jpg",
    linkedin_url: "https://linkedin.com",
    lat: 19.4,
    lon: -99.1,
  },
  {
    id: "2",
    name: "Sebastián Morales",
    role: "Líder Comunitario",
    organization: "Red de Guardianes del Amazonas",
    country: "Colombia",
    category: "liderazgo",
    badge_text: "Amazonía",
    image_url: "https://randomuser.me/api/portraits/men/22.jpg",
    linkedin_url: "https://linkedin.com",
    lat: 4.7,
    lon: -74.1,
  },
  {
    id: "3",
    name: "Camila Fernández",
    role: "Investigadora de Ecosistemas",
    organization: "Universidad de Buenos Aires",
    country: "Argentina",
    category: "enfoque",
    badge_text: "Patagonia",
    image_url: "https://randomuser.me/api/portraits/women/33.jpg",
    linkedin_url: "https://linkedin.com",
    lat: -34.6,
    lon: -58.4,
  },
  {
    id: "4",
    name: "Andrés Huanca",
    role: "Defensor de Territorios Indígenas",
    organization: "CONAMAQ",
    country: "Bolivia",
    category: "liderazgo",
    badge_text: "Altiplano",
    image_url: "https://randomuser.me/api/portraits/men/44.jpg",
    linkedin_url: "",
    lat: -16.5,
    lon: -68.1,
  },
  {
    id: "5",
    name: "Lucía Vargas",
    role: "Coordinadora de Reforestación",
    organization: "Semillas de Vida",
    country: "Perú",
    category: "bioregion",
    badge_text: "Bosque Nublado",
    image_url: "https://randomuser.me/api/portraits/women/55.jpg",
    linkedin_url: "https://linkedin.com",
    lat: -12.0,
    lon: -77.0,
  },
  {
    id: "6",
    name: "Diego Almeida",
    role: "Activista Climático",
    organization: "Acción Ecológica",
    country: "Ecuador",
    category: "enfoque",
    badge_text: "Galápagos",
    image_url: "https://randomuser.me/api/portraits/men/66.jpg",
    linkedin_url: "https://linkedin.com",
    lat: -0.2,
    lon: -78.5,
  },
  {
    id: "7",
    name: "Renata Souza",
    role: "Guardiana del Cerrado",
    organization: "Instituto Socioambiental",
    country: "Brasil",
    category: "bioregion",
    badge_text: "Cerrado",
    image_url: "https://randomuser.me/api/portraits/women/77.jpg",
    linkedin_url: "https://linkedin.com",
    lat: -15.8,
    lon: -47.9,
  },
  {
    id: "8",
    name: "Carlos Mendoza",
    role: "Educador Ambiental",
    organization: "Ecoescuelas Chile",
    country: "Chile",
    category: "enfoque",
    badge_text: "Patagonia Chilena",
    image_url: "https://randomuser.me/api/portraits/men/88.jpg",
    linkedin_url: "https://linkedin.com",
    lat: -33.5,
    lon: -70.7,
  },
  {
    id: "9",
    name: "Isabel Recalde",
    role: "Gestora de Áreas Protegidas",
    organization: "CONAP",
    country: "Guatemala",
    category: "bioregion",
    badge_text: "Petén",
    image_url: "https://randomuser.me/api/portraits/women/9.jpg",
    linkedin_url: "https://linkedin.com",
    lat: 14.6,
    lon: -90.5,
  },
  {
    id: "10",
    name: "Mateo González",
    role: "Fotógrafo de Naturaleza",
    organization: "Nature LATAM",
    country: "Uruguay",
    category: "liderazgo",
    badge_text: "Humedales",
    image_url: "https://randomuser.me/api/portraits/men/10.jpg",
    linkedin_url: "https://linkedin.com",
    lat: -34.9,
    lon: -56.2,
  },
  {
    id: "11",
    name: "Sofía Chávez",
    role: "Abogada Ambiental",
    organization: "Dejusticia Venezuela",
    country: "Venezuela",
    category: "enfoque",
    badge_text: "Delta del Orinoco",
    image_url: "https://randomuser.me/api/portraits/women/21.jpg",
    linkedin_url: "https://linkedin.com",
    lat: 10.5,
    lon: -66.9,
  },
  {
    id: "12",
    name: "Pablo Ortiz",
    role: "Líder Indígena",
    organization: "Coordinadora Arauco Malleco",
    country: "Chile",
    category: "liderazgo",
    badge_text: "Araucanía",
    image_url: "https://randomuser.me/api/portraits/men/32.jpg",
    linkedin_url: "",
    lat: -38.7,
    lon: -72.6,
  },
];

// Simula una llamada asíncrona (para reemplazar la API de Base44)
export async function fetchGuardians() {
  return new Promise((resolve) => {
    setTimeout(() => resolve(GUARDIANS_DATA), 300);
  });
}
